// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM8fJgP1t25pGin57-DgLeUeryW8J2BD0',
    appId: '1:428875645108:web:1634c2ffbe1438f0c1d7e1',
    messagingSenderId: '428875645108',
    projectId: 'login-flutter-app-7a48f',
    authDomain: 'login-flutter-app-7a48f.firebaseapp.com',
    storageBucket: 'login-flutter-app-7a48f.appspot.com',
    measurementId: 'G-ZK5D86XS3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUHxRHyGihh3y70M4jkvexBpvBGfmB-Lo',
    appId: '1:428875645108:android:409528e5fd692e02c1d7e1',
    messagingSenderId: '428875645108',
    projectId: 'login-flutter-app-7a48f',
    storageBucket: 'login-flutter-app-7a48f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVrYzOhtk845PotA5lQoSv7YCK7bXn5sM',
    appId: '1:428875645108:ios:c89d88d4dd2d97f5c1d7e1',
    messagingSenderId: '428875645108',
    projectId: 'login-flutter-app-7a48f',
    storageBucket: 'login-flutter-app-7a48f.appspot.com',
    iosClientId: '428875645108-omnf2v1s42idr3akvh2vba3jg9aul2jh.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVrYzOhtk845PotA5lQoSv7YCK7bXn5sM',
    appId: '1:428875645108:ios:19926943a6255291c1d7e1',
    messagingSenderId: '428875645108',
    projectId: 'login-flutter-app-7a48f',
    storageBucket: 'login-flutter-app-7a48f.appspot.com',
    iosClientId: '428875645108-i581ffcidog078vhp7hpqint3k84fd8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFlutterApp.RunnerTests',
  );
}
